### ISSUE TITLE
Clarify relationship between XRP secret and keypair.privateKey

### ISSUE THREAD

**Issue by michielbdejong** [sharafian/moneyd#3]
For my XRP account, I have a 'seed', a 'keypair' (containing privateKey and publicKey) and an 'address'. I do not have any 'xrp secret' as required in the readme. What should I do? Use keypair.privateKey instead? In upper-case hex encoding?

**Comment by emschwartz** [comment]
The secret/ seed is the thing that starts with `s` and is base58 encoded

**Comment by michielbdejong** [comment]
Thanks!
